### ISSUE TITLE
Bug of detection

### ISSUE THREAD

**Issue by carcaschoi** [borntohonk/NeutOS#1]
The latest version of neutos(https://github.com/borntohonk/NeutOS/releases/tag/0.19.0-9a1172cc) is detected as AMS but ot NEU

So hbg shop cannot show games image now

**Comment by borntohonk** [comment]
> The latest version of neutos(https://github.com/borntohonk/NeutOS/releases/tag/0.19.0-9a1172cc) is detected as AMS but ot NEU
> 
> So hbg shop cannot show games image now

I have reverted that functionality intentionally for now
