### ISSUE TITLE
Games ocassionally crash on launch with the new 19 update.

### ISSUE THREAD

**Issue by ElBori82** [borntohonk/NeutOS#2]
Games ocassionally crash on launch with the new 19 update. This was not an issue before on 18. Game will start after 2 or 3 tries but I have not played long sessions to determin if they will crash after they launch.

**Comment by borntohonk** [comment]
> Games ocassionally crash on launch with the new 19 update. This was not an issue before on 18. Game will start after 2 or 3 tries but I have not played long sessions to determin if they will crash after they launch.

There have been changes to NCM and PGL within atmosphere, that neutos is based off of, if you submit a proper report to their repository ( https://github.com/Atmosphere-NX/Atmosphere/issues ) using the bug report template ( https://github.com/Atmosphere-NX/Atmosphere/blob/master/.github/ISSUE_TEMPLATE/bug_report.md )
