### ISSUE TITLE
When updating Neutos, don't delete 'contents' folder (or make a backup).

### ISSUE THREAD

**Issue by lborruto** [borntohonk/NEUTOS#3]
When updating Neutos from the switch direclty, the updater will by default erase the 'atmosphere' folder, and thus the 'contents' folder too. In this 'contents' folder there can be many folder for cheats, game mod or addons like Tesla Overlay.
Maybe there can be an option to not delete the folders in, except for those from atmosphere?

**Comment by borntohonk** [comment]
@lborruto read the neutos-updater source code before you make wild remarks like this. It doesn't delete any folders.
