### ISSUE TITLE
hbmenu.nro

### ISSUE THREAD

**Issue by ray1025** [borntohonk/NeutOS#4]
NeutOS-0.19.5-master-9df13781+hbl-2.4.1+hbmenu-3.4.1+hekate-5.5.8+patches.zip

The latest package is missing "hbmenu.nro".

**Comment by borntohonk** [comment]
i'll fix it

**Comment by borntohonk** [comment]
auto-publishing would fetch https://github.com/switchbrew/nx-hbmenu and the release would contain "hbmenu.nro", now it's "nx-hbmenu.nro". Have adapted and corrected the issue for future releases @ray1025

**Comment by ray1025** [comment]
Many thanks
