### ISSUE TITLE
Updating from OS 12.0.1 causes infinite Nintendo Switch screen

### ISSUE THREAD

**Issue by Hack3Rz4LIFE** [borntohonk/NeutOS#5]
After installing the latest release of NeutOS onto my SD Card I can no longer boot. My switch is on whatever NeutOS version was relevant to OS 12.0.1, and I've currently reverted for the moment using backups I created before attempting to update. 

I have attempted fresh installs of both the atmosphere and bootloader folders, as well as boot.dat and boot.ini and I've tried renaming the sept folder to sept-old. None of these things helped. My switch is set to AutoRCM and I'm booting using the included payload.bin for the current NeutOS variant (Which reports itself as AMS19.2|E)

When I moved up from 11.0 to 12.01 the order of operations I used was:

* Update NeutOS files on SD Card
* Boot Switch, update to latest OS via Daybreak
* Reboot again

Currently due to the stuck screen at the Nintendo Switch logo I cannot proceed to step 2. 

This could very well be user error if the procedure I just described is no longer relevant.

**Comment by borntohonk** [comment]
> After installing the latest release of NeutOS onto my SD Card I can no longer boot. My switch is on whatever NeutOS version was relevant to OS 12.0.1, and I've currently reverted for the moment using backups I created before attempting to update.
> 
> I have attempted fresh installs of both the atmosphere and bootloader folders, as well as boot.dat and boot.ini and I've tried renaming the sept folder to sept-old. None of these things helped. My switch is set to AutoRCM and I'm booting using the included payload.bin for the current NeutOS variant (Which reports itself as AMS19.2|E)
> 
> When I moved up from 11.0 to 12.01 the order of operations I used was:
> 
> * Update NeutOS files on SD Card
> * Boot Switch, update to latest OS via Daybreak
> * Reboot again
> 
> Currently due to the stuck screen at the Nintendo Switch logo I cannot proceed to step 2.
> 
> This could very well be user error if the procedure I just described is no longer relevant.

@Hack3Rz4LIFE Not a Neutos issue, sept isn't used anymore. And NeutOS definitively isn't based on ams 19. Suggest you wipe clean your sd card from old trash (literally delete the pre-existing atmosphere folder).
